def shared_pods
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '11.0'
  use_frameworks!
  
  # - Loverde Co. Essentials
  pod 'LCEssentials'

  # - UI Configs
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  pod 'Alamofire'
end

target 'ImgurAppTest' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete('CODE_SIGNING_ALLOWED')
    config.build_settings.delete('CODE_SIGNING_REQUIRED')
  end
end

